!*********/files/**************************
      integer*4 isfileopen
      CHARACTER*256 CONFIG,schFile,THMOFILE,FILEIN,outfil,hydroPFile,modelFile,modelOutputFile
      character*256 inputMineralFile,BulkRockCompositionFile,modelOutputFileBase,CanvasFileName,ModelLogFile,ModelStuffFile,	&
      		PolyModelInfoFile
      common /files/CONFIG,schFile,thmoFile,filein,outfil,hydroPFile,inputMineralFile,isfileopen,   &
      		bulkrockcompositionfile,modelFile,modelOutputFile,modelOutputFileBase,CanvasFileName,ModelLogFile,ModelStuffFile, &
      		PolyModelInfoFile
!***********************************
